# Generated by Django 3.1.4 on 2023-07-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField()),
                ('alarm_desc', models.CharField(max_length=1024)),
                ('first_alarm_time', models.DateTimeField()),
                ('alarm_times', models.PositiveIntegerField()),
                ('last_updated_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '告警日志',
                'verbose_name_plural': '告警日志',
                'db_table': 'dma_alarm_log',
            },
        ),
    ]
