# Generated by Django 3.1.4 on 2023-08-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSnapShot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.IntegerField()),
                ('stock_info', models.JSONField()),
                ('zz_info', models.JSONField()),
                ('zz_summary_info', models.JSONField()),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '在制快照',
                'verbose_name_plural': '在制快照',
                'db_table': 'dma_snap_shot',
            },
        ),
        migrations.CreateModel(
            name='StockHistorySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.IntegerField()),
                ('process_name', models.CharField(max_length=256)),
                ('route_name', models.CharField(max_length=256)),
                ('trains_num', models.IntegerField()),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '历史在制统计信息',
                'verbose_name_plural': '历史在制统计信息',
                'db_table': 'dma_stock_history_summary',
            },
        ),
        migrations.AddField(
            model_name='alarmlog',
            name='md5_data',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
