# Generated by Django 3.1.4 on 2023-08-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20230801_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistorysummary',
            name='stock_type',
        ),
        migrations.RemoveField(
            model_name='stockhistorysummary',
            name='trains_num',
        ),
        migrations.AddField(
            model_name='stockhistorysummary',
            name='agv_trains_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockhistorysummary',
            name='cache_trains_num',
            field=models.IntegerField(default=0),
        ),
    ]
