# Generated by Django 3.1.4 on 2023-08-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20230801_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasnapshot',
            name='tag',
            field=models.CharField(db_index=True, default=1, max_length=256),
            preserve_default=False,
        ),
    ]
