# Generated by Django 3.1.4 on 2023-07-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='process_name',
            field=models.CharField(blank=True, help_text='工艺段名称', max_length=256, null=True, verbose_name='工艺段名称'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_location_type',
            field=models.IntegerField(default=1, help_text='站台类型(1:站台 2:堆栈)', verbose_name='站台类型(1:站台 2:堆栈)'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='axis1_package_name',
            field=models.CharField(blank=True, help_text='AGV轴1包号', max_length=1024, null=True, verbose_name='AGV轴1包号'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='axis2_package_name',
            field=models.CharField(blank=True, help_text='AGV轴2包号', max_length=1024, null=True, verbose_name='AGV轴2包号'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='axis3_package_name',
            field=models.CharField(blank=True, help_text='AGV轴3包号', max_length=1024, null=True, verbose_name='AGV轴3包号'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='axis4_package_name',
            field=models.CharField(blank=True, help_text='AGV轴4包号', max_length=1024, null=True, verbose_name='AGV轴4包号'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['process_name'], name='dma_tasks_process_275c8d_idx'),
        ),
    ]
