# Generated by Django 3.1.4 on 2023-08-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv', '0002_auto_20230726_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcscommand',
            name='task_delay_time',
            field=models.IntegerField(default=0, help_text='任务延迟时间', verbose_name='任务延迟时间'),
        ),
    ]
