# Generated by Django 3.1.4 on 2023-08-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv', '0003_rcscommand_task_delay_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheDeviceTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ID', models.CharField(max_length=256)),
                ('material_type', models.CharField(max_length=256)),
                ('tag', models.CharField(blank=True, max_length=256, null=True)),
                ('task_type', models.IntegerField()),
                ('task_state', models.IntegerField()),
                ('traceback_state', models.IntegerField()),
                ('request_allowed', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '堆栈任务',
                'verbose_name_plural': '堆栈任务',
                'db_table': 'dam_cache_device_tasks',
            },
        ),
        migrations.AddIndex(
            model_name='cachedevicetasks',
            index=models.Index(fields=['device_ID'], name='dam_cache_d_device__0a49fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedevicetasks',
            index=models.Index(fields=['task_type'], name='dam_cache_d_task_ty_5acc21_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedevicetasks',
            index=models.Index(fields=['task_state'], name='dam_cache_d_task_st_ed1438_idx'),
        ),
    ]
