# Generated by Django 3.1.4 on 2023-08-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv', '0004_auto_20230809_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='receive_time',
            field=models.DateTimeField(blank=True, help_text='接料完成时间', null=True, verbose_name='接料完成时间'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='origin_platform_ID',
            field=models.CharField(blank=True, help_text='来源站台ID', max_length=256, null=True, verbose_name='来源站台ID'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='origin_platform_name',
            field=models.CharField(blank=True, help_text='来源站台名称', max_length=256, null=True, verbose_name='来源站台名称'),
        ),
    ]
