# Generated by Django 3.1.4 on 2023-08-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv', '0005_auto_20230810_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_no',
            field=models.CharField(help_text='任务号', max_length=128, unique=True, verbose_name='任务号'),
        ),
    ]
