# Generated by Django 3.1.4 on 2023-08-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv', '0006_auto_20230817_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedevicetasks',
            name='equip_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
