# Generated by Django 3.1.4 on 2023-09-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv', '0007_cachedevicetasks_equip_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedevicestock',
            name='layoff_time',
            field=models.CharField(blank=True, help_text='下料时间', max_length=19, null=True),
        ),
    ]
