# Generated by Django 3.1.4 on 2023-09-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv', '0009_auto_20230914_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedevicestock',
            name='storge_time',
            field=models.IntegerField(default=0, help_text='堆栈存储时间', verbose_name='堆栈存储时间', blank=True, null=True),
        ),
    ]
