# Generated by Django 3.1 on 2023-07-22 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workarea',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_workarea_related', related_query_name='c_basics_workareas', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='workarea',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_workarea_related', related_query_name='d_basics_workareas', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='workarea',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_workarea_related', related_query_name='u_basics_workareas', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='routingschema',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_routingschema_related', related_query_name='c_basics_routingschemas', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='routingschema',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_routingschema_related', related_query_name='d_basics_routingschemas', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='routingschema',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_routingschema_related', related_query_name='u_basics_routingschemas', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='restlocationrouterelation',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_restlocationrouterelation_related', related_query_name='c_basics_restlocationrouterelations', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='restlocationrouterelation',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_restlocationrouterelation_related', related_query_name='d_basics_restlocationrouterelations', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='restlocationrouterelation',
            name='group',
            field=models.ForeignKey(help_text='站台定线组id', on_delete=django.db.models.deletion.CASCADE, related_name='r_rls', to='basics.platformgroup', verbose_name='站台定线组id'),
        ),
        migrations.AddField(
            model_name='restlocationrouterelation',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_restlocationrouterelation_related', related_query_name='u_basics_restlocationrouterelations', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='restlocationrouterelation',
            name='rest_location',
            field=models.ForeignKey(help_text='休息位id', on_delete=django.db.models.deletion.PROTECT, to='basics.restlocation', verbose_name='休息位id'),
        ),
        migrations.AddField(
            model_name='restlocation',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_restlocation_related', related_query_name='c_basics_restlocations', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='restlocation',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_restlocation_related', related_query_name='d_basics_restlocations', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='restlocation',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_restlocation_related', related_query_name='u_basics_restlocations', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='restlocation',
            name='processes',
            field=models.ManyToManyField(through='basics.ProcessRestLocationRelation', to='basics.ProcessSection'),
        ),
        migrations.AddField(
            model_name='restlocation',
            name='working_area',
            field=models.ForeignKey(db_constraint=False, help_text='工作区ID', on_delete=django.db.models.deletion.PROTECT, to='basics.workarea', verbose_name='工作区ID'),
        ),
        migrations.AddField(
            model_name='processsection',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_processsection_related', related_query_name='c_basics_processsections', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='processsection',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_processsection_related', related_query_name='d_basics_processsections', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='processsection',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_processsection_related', related_query_name='u_basics_processsections', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='processsection',
            name='source_process',
            field=models.ForeignKey(blank=True, help_text='源工艺段id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_sources', to='basics.processsection', verbose_name='源工艺段id'),
        ),
        migrations.AddField(
            model_name='processsection',
            name='target_process',
            field=models.ForeignKey(blank=True, help_text='目标工艺段id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_targets', to='basics.processsection', verbose_name='目标工艺段id'),
        ),
        migrations.AddField(
            model_name='processsection',
            name='working_area',
            field=models.ForeignKey(db_constraint=False, help_text='工作区id', on_delete=django.db.models.deletion.PROTECT, to='basics.workarea', verbose_name='工作区id'),
        ),
        migrations.AddField(
            model_name='processrestlocationrelation',
            name='process',
            field=models.ForeignKey(help_text='工艺段id', on_delete=django.db.models.deletion.CASCADE, to='basics.processsection', verbose_name='工艺段id'),
        ),
        migrations.AddField(
            model_name='processrestlocationrelation',
            name='rest_location',
            field=models.ForeignKey(help_text='休息停靠位id', on_delete=django.db.models.deletion.CASCADE, to='basics.restlocation', verbose_name='休息停靠位id'),
        ),
        migrations.AddField(
            model_name='processcachedevicerelation',
            name='cache_device',
            field=models.ForeignKey(help_text='堆栈id', on_delete=django.db.models.deletion.CASCADE, related_name='device_process', to='basics.cachedeviceinfo', verbose_name='堆栈id'),
        ),
        migrations.AddField(
            model_name='processcachedevicerelation',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_processcachedevicerelation_related', related_query_name='c_basics_processcachedevicerelations', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='processcachedevicerelation',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_processcachedevicerelation_related', related_query_name='d_basics_processcachedevicerelations', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='processcachedevicerelation',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_processcachedevicerelation_related', related_query_name='u_basics_processcachedevicerelations', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='processcachedevicerelation',
            name='process',
            field=models.ForeignKey(help_text='工艺段id', on_delete=django.db.models.deletion.CASCADE, to='basics.processsection', verbose_name='工艺段id'),
        ),
        migrations.AddField(
            model_name='platformrealinfo',
            name='platform_info',
            field=models.OneToOneField(help_text='站台id', on_delete=django.db.models.deletion.CASCADE, related_name='platform_real_info', to='basics.platforminfo', verbose_name='站台id'),
        ),
        migrations.AddField(
            model_name='platformpart',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_platformpart_related', related_query_name='c_basics_platformparts', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='platformpart',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_platformpart_related', related_query_name='d_basics_platformparts', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='platformpart',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_platformpart_related', related_query_name='u_basics_platformparts', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='platformpart',
            name='platform_info',
            field=models.ForeignKey(help_text='站台id', on_delete=django.db.models.deletion.CASCADE, related_name='platform_parts', to='basics.platforminfo', verbose_name='站台id'),
        ),
        migrations.AddField(
            model_name='platforminfo',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_platforminfo_related', related_query_name='c_basics_platforminfos', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='platforminfo',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_platforminfo_related', related_query_name='d_basics_platforminfos', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='platforminfo',
            name='group',
            field=models.ForeignKey(blank=True, help_text='归属设备组id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_plts', to='basics.platformgroup', verbose_name='归属设备组id'),
        ),
        migrations.AddField(
            model_name='platforminfo',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_platforminfo_related', related_query_name='u_basics_platforminfos', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='platforminfo',
            name='location_group',
            field=models.ForeignKey(blank=True, help_text='休息位组id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lc_plts', to='basics.locationgroup', verbose_name='休息位组id'),
        ),
        migrations.AddField(
            model_name='platforminfo',
            name='pre_group',
            field=models.ForeignKey(blank=True, help_text='预定线归属设备组id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_pre_plts', to='basics.platformgroup', verbose_name='预定线归属设备组id'),
        ),
        migrations.AddField(
            model_name='platforminfo',
            name='process',
            field=models.ForeignKey(help_text='工艺段id', on_delete=django.db.models.deletion.PROTECT, related_name='process_platforms', to='basics.processsection'),
        ),
        migrations.AddField(
            model_name='platforminfo',
            name='rejected_platform',
            field=models.ManyToManyField(blank=True, db_table='shunt_reject_platform_relation', help_text='互斥站台id列表', related_name='_platforminfo_rejected_platform_+', to='basics.PlatFormInfo', verbose_name='互斥站台id列表'),
        ),
        migrations.AddField(
            model_name='platforminfo',
            name='shunt_platform_group',
            field=models.ManyToManyField(blank=True, db_table='shunt_platform_group_relation', help_text='分流设备组id列表', to='basics.PlatformGroup', verbose_name='分流设备组id列表'),
        ),
        migrations.AddField(
            model_name='platforminfo',
            name='wet_limit_group',
            field=models.ForeignKey(blank=True, help_text='湿区设备限制组id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wet_plts', to='basics.platformgroup', verbose_name='湿区设备限制组id'),
        ),
        migrations.AddField(
            model_name='platformgroup',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_platformgroup_related', related_query_name='c_basics_platformgroups', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='platformgroup',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_platformgroup_related', related_query_name='d_basics_platformgroups', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='platformgroup',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_platformgroup_related', related_query_name='u_basics_platformgroups', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='platformgroup',
            name='process',
            field=models.ForeignKey(help_text='工艺段id', on_delete=django.db.models.deletion.CASCADE, related_name='process_groups', to='basics.processsection'),
        ),
        migrations.AddField(
            model_name='platformgroup',
            name='route_schema',
            field=models.ForeignKey(help_text='定线id', on_delete=django.db.models.deletion.CASCADE, related_name='r_groups', to='basics.routingschema', verbose_name='定线id'),
        ),
        migrations.AddField(
            model_name='locationgrouprelation',
            name='location',
            field=models.ForeignKey(help_text='休息位', on_delete=django.db.models.deletion.PROTECT, to='basics.location', verbose_name='休息位'),
        ),
        migrations.AddField(
            model_name='locationgrouprelation',
            name='location_group',
            field=models.ForeignKey(help_text='休息位组', on_delete=django.db.models.deletion.CASCADE, to='basics.locationgroup', verbose_name='休息位组'),
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_locationgroup_related', related_query_name='c_basics_locationgroups', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_locationgroup_related', related_query_name='d_basics_locationgroups', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_locationgroup_related', related_query_name='u_basics_locationgroups', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='locations',
            field=models.ManyToManyField(through='basics.LocationGroupRelation', to='basics.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_location_related', related_query_name='c_basics_locations', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='location',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_location_related', related_query_name='d_basics_locations', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='location',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_location_related', related_query_name='u_basics_locations', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='globalcodetype',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_globalcodetype_related', related_query_name='c_basics_globalcodetypes', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='globalcodetype',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_globalcodetype_related', related_query_name='d_basics_globalcodetypes', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='globalcodetype',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_globalcodetype_related', related_query_name='u_basics_globalcodetypes', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='globalcode',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_globalcode_related', related_query_name='c_basics_globalcodes', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='globalcode',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_globalcode_related', related_query_name='d_basics_globalcodes', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='globalcode',
            name='global_type',
            field=models.ForeignKey(help_text='全局类型ID', on_delete=django.db.models.deletion.PROTECT, related_name='global_codes', to='basics.globalcodetype', verbose_name='全局类型ID'),
        ),
        migrations.AddField(
            model_name='globalcode',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_globalcode_related', related_query_name='u_basics_globalcodes', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='emptycacherouteschema',
            name='cache_info',
            field=models.OneToOneField(help_text='堆栈id', on_delete=django.db.models.deletion.PROTECT, related_name='c_route', to='basics.cachedeviceinfo', verbose_name='堆栈id'),
        ),
        migrations.AddField(
            model_name='emptycacherouteschema',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_emptycacherouteschema_related', related_query_name='c_basics_emptycacherouteschemas', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='emptycacherouteschema',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_emptycacherouteschema_related', related_query_name='d_basics_emptycacherouteschemas', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='emptycacherouteschema',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_emptycacherouteschema_related', related_query_name='u_basics_emptycacherouteschemas', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='emptycacherouteschema',
            name='target_platforms',
            field=models.ManyToManyField(db_table='bdm_cache_route_platform_relation', related_name='p_cetrs', to='basics.PlatFormInfo'),
        ),
        migrations.AddField(
            model_name='emptybasketrouteschema',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_emptybasketrouteschema_related', related_query_name='c_basics_emptybasketrouteschemas', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='emptybasketrouteschema',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_emptybasketrouteschema_related', related_query_name='d_basics_emptybasketrouteschemas', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='emptybasketrouteschema',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_emptybasketrouteschema_related', related_query_name='u_basics_emptybasketrouteschemas', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='emptybasketrouteschema',
            name='platform_info',
            field=models.OneToOneField(help_text='站台id', on_delete=django.db.models.deletion.PROTECT, related_name='p_route', to='basics.platforminfo', verbose_name='站台id'),
        ),
        migrations.AddField(
            model_name='emptybasketrouteschema',
            name='target_platforms',
            field=models.ManyToManyField(db_table='bdm_route_platform_relation', related_name='p_etrs', to='basics.PlatFormInfo'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_configuration_related', related_query_name='c_basics_configurations', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_configuration_related', related_query_name='d_basics_configurations', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_configuration_related', related_query_name='u_basics_configurations', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='cachedevicerouterelation',
            name='cache_device',
            field=models.ForeignKey(help_text='缓存堆栈id', on_delete=django.db.models.deletion.PROTECT, to='basics.cachedeviceinfo', verbose_name='缓存堆栈id'),
        ),
        migrations.AddField(
            model_name='cachedevicerouterelation',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_cachedevicerouterelation_related', related_query_name='c_basics_cachedevicerouterelations', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='cachedevicerouterelation',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_cachedevicerouterelation_related', related_query_name='d_basics_cachedevicerouterelations', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='cachedevicerouterelation',
            name='group',
            field=models.ForeignKey(help_text='站台定线组id', on_delete=django.db.models.deletion.CASCADE, to='basics.platformgroup', verbose_name='站台定线组id'),
        ),
        migrations.AddField(
            model_name='cachedevicerouterelation',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_cachedevicerouterelation_related', related_query_name='u_basics_cachedevicerouterelations', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='cachedeviceprerouterelation',
            name='cache_device',
            field=models.ForeignKey(help_text='缓存堆栈id', on_delete=django.db.models.deletion.PROTECT, to='basics.cachedeviceinfo', verbose_name='缓存堆栈id'),
        ),
        migrations.AddField(
            model_name='cachedeviceprerouterelation',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_cachedeviceprerouterelation_related', related_query_name='c_basics_cachedeviceprerouterelations', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='cachedeviceprerouterelation',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_cachedeviceprerouterelation_related', related_query_name='d_basics_cachedeviceprerouterelations', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='cachedeviceprerouterelation',
            name='group',
            field=models.ForeignKey(help_text='站台定线组id', on_delete=django.db.models.deletion.CASCADE, to='basics.platformgroup', verbose_name='站台定线组id'),
        ),
        migrations.AddField(
            model_name='cachedeviceprerouterelation',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_cachedeviceprerouterelation_related', related_query_name='u_basics_cachedeviceprerouterelations', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='cachedevicepart',
            name='cache_device',
            field=models.ForeignKey(help_text='堆栈id', on_delete=django.db.models.deletion.CASCADE, related_name='device_parts', to='basics.cachedeviceinfo', verbose_name='堆栈id'),
        ),
        migrations.AddField(
            model_name='cachedevicepart',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_cachedevicepart_related', related_query_name='c_basics_cachedeviceparts', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='cachedevicepart',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_cachedevicepart_related', related_query_name='d_basics_cachedeviceparts', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='cachedevicepart',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_cachedevicepart_related', related_query_name='u_basics_cachedeviceparts', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='cachedeviceinfo',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_basics_cachedeviceinfo_related', related_query_name='c_basics_cachedeviceinfos', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='cachedeviceinfo',
            name='delete_user',
            field=models.ForeignKey(blank=True, help_text='删除人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_basics_cachedeviceinfo_related', related_query_name='d_basics_cachedeviceinfos', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='cachedeviceinfo',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_basics_cachedeviceinfo_related', related_query_name='u_basics_cachedeviceinfos', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='cachedeviceinfo',
            name='processes',
            field=models.ManyToManyField(through='basics.ProcessCacheDeviceRelation', to='basics.ProcessSection'),
        ),
        migrations.AddField(
            model_name='cachedeviceinfo',
            name='working_area',
            field=models.ForeignKey(db_constraint=False, help_text='工作区id', on_delete=django.db.models.deletion.PROTECT, to='basics.workarea', verbose_name='工作区id'),
        ),
        migrations.AlterUniqueTogether(
            name='platformgroup',
            unique_together={('route_schema', 'process', 'group_type')},
        ),
    ]
