# Generated by Django 3.1 on 2023-07-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_auto_20230722_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_synced',
            field=models.BooleanField(default=False, help_text='是否同步到RCS', verbose_name='是否同步到RCS'),
        ),
    ]
