# Generated by Django 3.1 on 2023-07-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_location_is_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforminfo',
            name='location_group',
            field=models.ForeignKey(blank=True, help_text='休息位组id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lc_plts', to='basics.locationgroup', verbose_name='休息位组id'),
        ),
    ]
