# Generated by Django 3.1.4 on 2023-07-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0005_auto_20230724_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedevicepart',
            name='part_type',
            field=models.PositiveIntegerField(choices=[(1, 'AGV取货'), (2, 'AGV卸货')], help_text='部件类型', verbose_name='部件类型'),
        ),
        migrations.AlterField(
            model_name='platformpart',
            name='part_type',
            field=models.PositiveIntegerField(choices=[(1, 'AGV取货'), (2, 'AGV卸货')], help_text='部件类型', null=True, verbose_name='部件类型'),
        ),
    ]
