# Generated by Django 3.1.4 on 2023-08-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0008_auto_20230803_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platforminfo',
            name='wet_limit_group',
        ),
        migrations.AddField(
            model_name='platforminfo',
            name='wet_limit_groups',
            field=models.ManyToManyField(blank=True, db_table='wet_platform_group_relation', help_text='湿区设备限制组id列表', related_name='wet_plts', to='basics.PlatformGroup', verbose_name='湿区设备限制组id列表'),
        ),
    ]
