# Generated by Django 3.1.4 on 2023-08-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0009_auto_20230804_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processsection',
            name='process_code',
        ),
    ]
