# Generated by Django 3.1.4 on 2023-08-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0010_remove_processsection_process_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedeviceinfo',
            name='device_ID',
            field=models.CharField(help_text='站台ID', max_length=256, unique=True, verbose_name='站台ID'),
        ),
        migrations.AlterField(
            model_name='cachedeviceinfo',
            name='device_name',
            field=models.CharField(help_text='站台名称', max_length=256, unique=True, verbose_name='站台名称'),
        ),
        migrations.AlterField(
            model_name='emptybasketrouteschema',
            name='route_ID',
            field=models.CharField(help_text='定线ID', max_length=256, unique=True, verbose_name='定线ID'),
        ),
        migrations.AlterField(
            model_name='emptybasketrouteschema',
            name='route_name',
            field=models.CharField(help_text='定线名称', max_length=256, unique=True, verbose_name='定线名称'),
        ),
        migrations.AlterField(
            model_name='emptycacherouteschema',
            name='route_ID',
            field=models.CharField(help_text='定线ID', max_length=256, unique=True, verbose_name='定线ID'),
        ),
        migrations.AlterField(
            model_name='emptycacherouteschema',
            name='route_name',
            field=models.CharField(help_text='定线名称', max_length=256, unique=True, verbose_name='定线名称'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(help_text='位置点名称', max_length=256, unique=True, verbose_name='位置点名称'),
        ),
        migrations.AlterField(
            model_name='locationgroup',
            name='group_code',
            field=models.CharField(help_text='休息位组编号', max_length=256, unique=True, verbose_name='休息位组编号'),
        ),
        migrations.AlterField(
            model_name='locationgroup',
            name='group_name',
            field=models.CharField(help_text='休息位组名称', max_length=256, unique=True, verbose_name='休息位组名称'),
        ),
        migrations.AlterField(
            model_name='platformgroup',
            name='group_ID',
            field=models.CharField(help_text='设备组ID', max_length=256, unique=True, verbose_name='设备组ID'),
        ),
        migrations.AlterField(
            model_name='platformgroup',
            name='group_name',
            field=models.CharField(help_text='设备组名称', max_length=256, unique=True, verbose_name='设备组名称'),
        ),
        migrations.AlterField(
            model_name='platforminfo',
            name='platform_ID',
            field=models.CharField(help_text='站台ID', max_length=256, unique=True, verbose_name='站台ID'),
        ),
        migrations.AlterField(
            model_name='platforminfo',
            name='platform_name',
            field=models.CharField(help_text='站台名称', max_length=256, unique=True, verbose_name='站台名称'),
        ),
        migrations.AlterField(
            model_name='platforminfo',
            name='shunt_platform_group',
            field=models.ManyToManyField(blank=True, db_table='shunt_platform_group_relation', help_text='分流设备组id列表', related_name='shunt_plts', to='basics.PlatformGroup', verbose_name='分流设备组id列表'),
        ),
        migrations.AlterField(
            model_name='processsection',
            name='process_ID',
            field=models.CharField(help_text='工艺段ID', max_length=256, unique=True, verbose_name='工艺段ID'),
        ),
        migrations.AlterField(
            model_name='processsection',
            name='process_name',
            field=models.CharField(help_text='工艺段名称', max_length=128, unique=True, verbose_name='工艺段名称'),
        ),
        migrations.AlterField(
            model_name='routingschema',
            name='route_ID',
            field=models.CharField(help_text='定线ID', max_length=256, unique=True, verbose_name='定线ID'),
        ),
        migrations.AlterField(
            model_name='routingschema',
            name='route_name',
            field=models.CharField(help_text='定线名称', max_length=256, unique=True, verbose_name='定线名称'),
        ),
    ]
