# Generated by Django 3.1.4 on 2023-08-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0011_auto_20230810_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformrealinfo',
            name='is_connected',
            field=models.BooleanField(default=True),
        ),
    ]
