# Generated by Django 3.1.4 on 2023-08-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0012_platformrealinfo_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformrealinfo',
            name='begin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
