# Generated by Django 3.1.4 on 2023-09-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0013_platformrealinfo_begin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedeviceinfo',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
