# Generated by Django 3.1.4 on 2023-10-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0014_cachedeviceinfo_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='workarea',
            name='agv_type',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
